
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Windows 10 Lite
 */
public class Courses extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Courses.class.getName());

    /**
     * Creates new form Courses
     */
    private String loggedInStudentID;

    public Courses() {
        this("");
        
    }

    public Courses(String studentID) {
        initComponents();
          setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        this.loggedInStudentID = studentID;

        DBConn db = new DBConn();

        if (!db.isCourseAvailable("NET101")) {
            net101Panel.setVisible(false);
        }
        if (!db.isCourseAvailable("MS102")) {
            ms102Panel.setVisible(false);
        }
        if (!db.isCourseAvailable("HCI101")) {
            hciPanel.setVisible(false);
        }
        if (!db.isCourseAvailable("SOSLIT")) {
            soslitPanel.setVisible(false);
        }
        if (!db.isCourseAvailable("PE3")) {
            pePanel.setVisible(false);
        }
        if (!db.isCourseAvailable("CC104")) {
            cc104Panel.setVisible(false);
        }
        if (!db.isCourseAvailable("IPT101")) {
            iptPanel.setVisible(false);
        }
        if (!db.isCourseAvailable("ITE1")) {
            itePanel.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register = new fancyui.FancyPanel();
        fancyPanel10 = new fancyui.FancyPanel();
        registerbtn3 = new fancyui.FancyButton();
        fancyLabel14 = new fancyui.FancyLabel();
        fancyLabel15 = new fancyui.FancyLabel();
        fancyPanel11 = new fancyui.FancyPanel();
        fancyLabel16 = new fancyui.FancyLabel();
        fancyPanel24 = new fancyui.FancyPanel();
        registerbtn10 = new fancyui.FancyButton();
        fancyLabel35 = new fancyui.FancyLabel();
        fancyLabel36 = new fancyui.FancyLabel();
        fancyPanel25 = new fancyui.FancyPanel();
        fancyLabel37 = new fancyui.FancyLabel();
        fancyPanel36 = new fancyui.FancyPanel();
        registerbtn16 = new fancyui.FancyButton();
        fancyLabel53 = new fancyui.FancyLabel();
        fancyLabel54 = new fancyui.FancyLabel();
        fancyPanel37 = new fancyui.FancyPanel();
        fancyLabel55 = new fancyui.FancyLabel();
        fancyPanel1 = new fancyui.FancyPanel();
        fancyPanel2 = new fancyui.FancyPanel();
        dashboard = new fancyui.FancyButton();
        fancyImage1 = new fancyui.FancyImage();
        fancyLabel2 = new fancyui.FancyLabel();
        mycourses = new fancyui.FancyButton();
        courses = new fancyui.FancyButton();
        profile = new fancyui.FancyButton();
        logout = new fancyui.FancyButton();
        jSeparator1 = new javax.swing.JSeparator();
        fancyLabel1 = new fancyui.FancyLabel();
        fancyLabel3 = new fancyui.FancyLabel();
        fancyPanel3 = new fancyui.FancyPanel();
        fancyLabel5 = new fancyui.FancyLabel();
        ms102Panel = new fancyui.FancyPanel();
        ms102btn = new fancyui.FancyButton();
        fancyLabel32 = new fancyui.FancyLabel();
        fancyLabel33 = new fancyui.FancyLabel();
        fancyPanel23 = new fancyui.FancyPanel();
        fancyLabel34 = new fancyui.FancyLabel();
        fancyLabel9 = new fancyui.FancyLabel();
        net101Panel = new fancyui.FancyPanel();
        fancyLabel38 = new fancyui.FancyLabel();
        fancyLabel39 = new fancyui.FancyLabel();
        fancyPanel27 = new fancyui.FancyPanel();
        fancyLabel40 = new fancyui.FancyLabel();
        fancyLabel8 = new fancyui.FancyLabel();
        net101btn = new fancyui.FancyButton();
        soslitPanel = new fancyui.FancyPanel();
        soslitbtn = new fancyui.FancyButton();
        fancyLabel41 = new fancyui.FancyLabel();
        fancyLabel42 = new fancyui.FancyLabel();
        fancyPanel29 = new fancyui.FancyPanel();
        fancyLabel43 = new fancyui.FancyLabel();
        fancyLabel11 = new fancyui.FancyLabel();
        hciPanel = new fancyui.FancyPanel();
        hcibtn = new fancyui.FancyButton();
        fancyLabel44 = new fancyui.FancyLabel();
        fancyLabel45 = new fancyui.FancyLabel();
        fancyPanel31 = new fancyui.FancyPanel();
        fancyLabel46 = new fancyui.FancyLabel();
        fancyLabel10 = new fancyui.FancyLabel();
        cc104Panel = new fancyui.FancyPanel();
        cc104btn = new fancyui.FancyButton();
        fancyLabel50 = new fancyui.FancyLabel();
        fancyLabel51 = new fancyui.FancyLabel();
        fancyPanel35 = new fancyui.FancyPanel();
        fancyLabel52 = new fancyui.FancyLabel();
        fancyLabel13 = new fancyui.FancyLabel();
        iptPanel = new fancyui.FancyPanel();
        ipt101btn = new fancyui.FancyButton();
        fancyLabel56 = new fancyui.FancyLabel();
        fancyLabel57 = new fancyui.FancyLabel();
        fancyPanel39 = new fancyui.FancyPanel();
        fancyLabel58 = new fancyui.FancyLabel();
        fancyLabel47 = new fancyui.FancyLabel();
        pePanel = new fancyui.FancyPanel();
        pe3btn = new fancyui.FancyButton();
        fancyLabel59 = new fancyui.FancyLabel();
        fancyLabel60 = new fancyui.FancyLabel();
        fancyPanel41 = new fancyui.FancyPanel();
        fancyLabel61 = new fancyui.FancyLabel();
        fancyLabel12 = new fancyui.FancyLabel();
        itePanel = new fancyui.FancyPanel();
        ite1btn = new fancyui.FancyButton();
        fancyLabel62 = new fancyui.FancyLabel();
        fancyLabel63 = new fancyui.FancyLabel();
        fancyPanel43 = new fancyui.FancyPanel();
        fancyLabel64 = new fancyui.FancyLabel();
        fancyLabel48 = new fancyui.FancyLabel();
        fancyButton2 = new fancyui.FancyButton();

        register.setGradientEnd(new java.awt.Color(0, 0, 0));
        register.setGradientStart(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register);
        register.setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        fancyPanel10.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel10.setBorderEnabled(true);
        fancyPanel10.setBorderThickness(2.0F);
        fancyPanel10.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel10.setSolidBackgroundEnabled(true);

        registerbtn3.setText("Register");
        registerbtn3.setBackgroundColor(new java.awt.Color(0, 0, 0));
        registerbtn3.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn3.addActionListener(this::registerbtn3ActionPerformed);

        fancyLabel14.setText("Networking 1");

        fancyLabel15.setText("Mon-Face to face - MV 304 6:00–08:00 AM· | Tue- Virtual Classrom 7:00–8:00 AM · 3 units");

        fancyPanel11.setGradientEnabled(false);
        fancyPanel11.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel11.setSolidBackgroundEnabled(true);

        fancyLabel16.setText("NET101");
        fancyLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel11Layout = new javax.swing.GroupLayout(fancyPanel11);
        fancyPanel11.setLayout(fancyPanel11Layout);
        fancyPanel11Layout.setHorizontalGroup(
            fancyPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel11Layout.setVerticalGroup(
            fancyPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel11Layout.createSequentialGroup()
                .addComponent(fancyLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel10Layout = new javax.swing.GroupLayout(fancyPanel10);
        fancyPanel10.setLayout(fancyPanel10Layout);
        fancyPanel10Layout.setHorizontalGroup(
            fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(registerbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel10Layout.setVerticalGroup(
            fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(registerbtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fancyPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fancyPanel24.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel24.setBorderEnabled(true);
        fancyPanel24.setBorderThickness(2.0F);
        fancyPanel24.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel24.setSolidBackgroundEnabled(true);

        registerbtn10.setText("Register");
        registerbtn10.setBackgroundColor(new java.awt.Color(0, 0, 0));
        registerbtn10.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn10.addActionListener(this::registerbtn10ActionPerformed);

        fancyLabel35.setText("Networking 1");

        fancyLabel36.setText("Mon-Face to face - MV 304 6:00–08:00 AM· | Tue- Virtual Classrom 7:00–8:00 AM · 3 units");

        fancyPanel25.setGradientEnabled(false);
        fancyPanel25.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel25.setSolidBackgroundEnabled(true);

        fancyLabel37.setText("NET101");
        fancyLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel25Layout = new javax.swing.GroupLayout(fancyPanel25);
        fancyPanel25.setLayout(fancyPanel25Layout);
        fancyPanel25Layout.setHorizontalGroup(
            fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel25Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel25Layout.setVerticalGroup(
            fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel25Layout.createSequentialGroup()
                .addComponent(fancyLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel24Layout = new javax.swing.GroupLayout(fancyPanel24);
        fancyPanel24.setLayout(fancyPanel24Layout);
        fancyPanel24Layout.setHorizontalGroup(
            fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(registerbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel24Layout.setVerticalGroup(
            fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel24Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(registerbtn10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fancyPanel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fancyPanel36.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel36.setBorderEnabled(true);
        fancyPanel36.setBorderThickness(2.0F);
        fancyPanel36.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel36.setSolidBackgroundEnabled(true);

        registerbtn16.setText("Register");
        registerbtn16.setBackgroundColor(new java.awt.Color(0, 0, 0));
        registerbtn16.setDefaultForeground(new java.awt.Color(255, 255, 255));
        registerbtn16.addActionListener(this::registerbtn16ActionPerformed);

        fancyLabel53.setText("Sosyedad at Literatura");

        fancyLabel54.setText("Wed-Face to face - MV 304 08:30–10:30 AM· | Th- Virtual Classrom 8:00–9:00 AM · 3 units");

        fancyPanel37.setGradientEnabled(false);
        fancyPanel37.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel37.setSolidBackgroundEnabled(true);

        fancyLabel55.setText("SOSLIT");
        fancyLabel55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel37Layout = new javax.swing.GroupLayout(fancyPanel37);
        fancyPanel37.setLayout(fancyPanel37Layout);
        fancyPanel37Layout.setHorizontalGroup(
            fancyPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel37Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel37Layout.setVerticalGroup(
            fancyPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel37Layout.createSequentialGroup()
                .addComponent(fancyLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel36Layout = new javax.swing.GroupLayout(fancyPanel36);
        fancyPanel36.setLayout(fancyPanel36Layout);
        fancyPanel36Layout.setHorizontalGroup(
            fancyPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(registerbtn16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel36Layout.setVerticalGroup(
            fancyPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel36Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel36Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fancyPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(registerbtn16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fancyPanel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fancyPanel1.setCornerRadius(0);
        fancyPanel1.setGradientEnabled(false);
        fancyPanel1.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel1.setGradientStart(new java.awt.Color(0, 0, 153));
        fancyPanel1.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel1.setSolidBackgroundEnabled(true);

        fancyPanel2.setCornerRadius(0);
        fancyPanel2.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyPanel2.setGradientStart(new java.awt.Color(0, 0, 153));

        dashboard.setText("Dashboard");
        dashboard.setBackgroundColor(new java.awt.Color(0, 0, 153));
        dashboard.setBorderColor(new java.awt.Color(0, 0, 153));
        dashboard.setCornerRadius(10);
        dashboard.setDefaultForeground(new java.awt.Color(255, 255, 255));
        dashboard.addActionListener(this::dashboardActionPerformed);

        fancyImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollixlogo.png"))); // NOI18N

        fancyLabel2.setForeground(new java.awt.Color(204, 204, 204));
        fancyLabel2.setText("Menu");

        mycourses.setText("My Courses");
        mycourses.setBackgroundColor(new java.awt.Color(0, 0, 153));
        mycourses.setBorderColor(new java.awt.Color(0, 0, 153));
        mycourses.setCornerRadius(10);
        mycourses.setDefaultForeground(new java.awt.Color(255, 255, 255));
        mycourses.addActionListener(this::mycoursesActionPerformed);

        courses.setText("Courses");
        courses.setBackgroundColor(new java.awt.Color(0, 0, 153));
        courses.setBorderColor(new java.awt.Color(0, 0, 153));
        courses.setCornerRadius(10);
        courses.setDefaultForeground(new java.awt.Color(255, 255, 255));
        courses.addActionListener(this::coursesActionPerformed);

        profile.setText("Profile");
        profile.setBackgroundColor(new java.awt.Color(0, 0, 153));
        profile.setBorderColor(new java.awt.Color(0, 0, 153));
        profile.setCornerRadius(10);
        profile.setDefaultForeground(new java.awt.Color(255, 255, 255));
        profile.addActionListener(this::profileActionPerformed);

        logout.setText("Logout");
        logout.setBackgroundColor(new java.awt.Color(0, 0, 153));
        logout.setBorderColor(new java.awt.Color(0, 0, 153));
        logout.setCornerRadius(10);
        logout.setDefaultForeground(new java.awt.Color(255, 255, 255));
        logout.setHoverBackground(new java.awt.Color(255, 51, 0));
        logout.addActionListener(this::logoutActionPerformed);

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mycourses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fancyPanel2Layout.createSequentialGroup()
                        .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(courses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(mycourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        fancyLabel1.setText("Available Courses");
        fancyLabel1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 24)); // NOI18N

        fancyLabel3.setText("BSIT 2nd Year subjects open for registration this term.");
        fancyLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        fancyPanel3.setBorderColor(new java.awt.Color(0, 0, 0));
        fancyPanel3.setBorderEnabled(true);
        fancyPanel3.setBorderThickness(2.0F);
        fancyPanel3.setGradientEnabled(false);
        fancyPanel3.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel3.setSolidBackgroundEnabled(true);

        fancyLabel5.setText("BSIT 2nd Year — Available Courses (27 total units)");

        ms102Panel.setBorderColor(new java.awt.Color(0, 0, 0));
        ms102Panel.setBorderEnabled(true);
        ms102Panel.setBorderThickness(2.0F);
        ms102Panel.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        ms102Panel.setSolidBackgroundEnabled(true);

        ms102btn.setText("Register");
        ms102btn.setBackgroundColor(new java.awt.Color(0, 0, 0));
        ms102btn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        ms102btn.addActionListener(this::ms102btnActionPerformed);

        fancyLabel32.setText("Qauntitative Methods with Modelling Simulation");

        fancyLabel33.setText("Mon-Face to face - MV 304 8:30–10:30 AM· | Tue- Virtual Classrom 8:00–9:00 AM · 3 units");

        fancyPanel23.setGradientEnabled(false);
        fancyPanel23.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel23.setSolidBackgroundEnabled(true);

        fancyLabel34.setText("MS102");
        fancyLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel23Layout = new javax.swing.GroupLayout(fancyPanel23);
        fancyPanel23.setLayout(fancyPanel23Layout);
        fancyPanel23Layout.setHorizontalGroup(
            fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel23Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel23Layout.setVerticalGroup(
            fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel23Layout.createSequentialGroup()
                .addComponent(fancyLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel9.setText("Mr.Cesar Canlas");

        javax.swing.GroupLayout ms102PanelLayout = new javax.swing.GroupLayout(ms102Panel);
        ms102Panel.setLayout(ms102PanelLayout);
        ms102PanelLayout.setHorizontalGroup(
            ms102PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms102PanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fancyPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(ms102PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms102PanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ms102PanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addComponent(ms102btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ms102PanelLayout.setVerticalGroup(
            ms102PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms102PanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ms102PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms102PanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ms102btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ms102PanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(fancyLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        net101Panel.setBorderColor(new java.awt.Color(0, 0, 0));
        net101Panel.setBorderEnabled(true);
        net101Panel.setBorderThickness(2.0F);
        net101Panel.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        net101Panel.setSolidBackgroundEnabled(true);

        fancyLabel38.setText("Networking 1");

        fancyLabel39.setText("Mon-Face to face - MV 304 6:00–08:00 AM· | Tue- Virtual Classrom 7:00–8:00 AM · 3 units");

        fancyPanel27.setGradientEnabled(false);
        fancyPanel27.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel27.setSolidBackgroundEnabled(true);

        fancyLabel40.setText("NET101");
        fancyLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel27Layout = new javax.swing.GroupLayout(fancyPanel27);
        fancyPanel27.setLayout(fancyPanel27Layout);
        fancyPanel27Layout.setHorizontalGroup(
            fancyPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel27Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel27Layout.setVerticalGroup(
            fancyPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel27Layout.createSequentialGroup()
                .addComponent(fancyLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel8.setText("Mr.Aldrine De Guzman");

        net101btn.setText("Register");
        net101btn.setBackgroundColor(new java.awt.Color(0, 0, 0));
        net101btn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        net101btn.addActionListener(this::net101btnActionPerformed);

        javax.swing.GroupLayout net101PanelLayout = new javax.swing.GroupLayout(net101Panel);
        net101Panel.setLayout(net101PanelLayout);
        net101PanelLayout.setHorizontalGroup(
            net101PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, net101PanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fancyPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(net101PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(net101btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        net101PanelLayout.setVerticalGroup(
            net101PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, net101PanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(net101PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fancyPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(net101PanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(net101PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fancyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(net101btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(net101PanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        soslitPanel.setBorderColor(new java.awt.Color(0, 0, 0));
        soslitPanel.setBorderEnabled(true);
        soslitPanel.setBorderThickness(2.0F);
        soslitPanel.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        soslitPanel.setSolidBackgroundEnabled(true);

        soslitbtn.setText("Register");
        soslitbtn.setBackgroundColor(new java.awt.Color(0, 0, 0));
        soslitbtn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        soslitbtn.addActionListener(this::soslitbtnActionPerformed);

        fancyLabel41.setText("Sosyedad at Literatura");

        fancyLabel42.setText("Wed-Face to face - MV 304 08:30–10:30 AM· | Th- Virtual Classrom 8:00–9:00 AM · 3 units");

        fancyPanel29.setGradientEnabled(false);
        fancyPanel29.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel29.setSolidBackgroundEnabled(true);

        fancyLabel43.setText("SOSLIT");
        fancyLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel29Layout = new javax.swing.GroupLayout(fancyPanel29);
        fancyPanel29.setLayout(fancyPanel29Layout);
        fancyPanel29Layout.setHorizontalGroup(
            fancyPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel29Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel29Layout.setVerticalGroup(
            fancyPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel29Layout.createSequentialGroup()
                .addComponent(fancyLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel11.setText("Ms.Azucena Lim");

        javax.swing.GroupLayout soslitPanelLayout = new javax.swing.GroupLayout(soslitPanel);
        soslitPanel.setLayout(soslitPanelLayout);
        soslitPanelLayout.setHorizontalGroup(
            soslitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, soslitPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fancyPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(soslitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soslitPanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(soslitPanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addComponent(soslitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        soslitPanelLayout.setVerticalGroup(
            soslitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, soslitPanelLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(soslitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soslitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(soslitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fancyPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(soslitPanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fancyLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        hciPanel.setBorderColor(new java.awt.Color(0, 0, 0));
        hciPanel.setBorderEnabled(true);
        hciPanel.setBorderThickness(2.0F);
        hciPanel.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        hciPanel.setSolidBackgroundEnabled(true);

        hcibtn.setText("Register");
        hcibtn.setBackgroundColor(new java.awt.Color(0, 0, 0));
        hcibtn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        hcibtn.addActionListener(this::hcibtnActionPerformed);

        fancyLabel44.setText("Introduction to Human Computer");

        fancyLabel45.setText("Mon-Face to face - MV 304 10:30–12:30 AM· | Tue- Virtual Classrom 9:00–10:00 AM · 3 units");

        fancyPanel31.setGradientEnabled(false);
        fancyPanel31.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel31.setSolidBackgroundEnabled(true);

        fancyLabel46.setText("HCI101");
        fancyLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel31Layout = new javax.swing.GroupLayout(fancyPanel31);
        fancyPanel31.setLayout(fancyPanel31Layout);
        fancyPanel31Layout.setHorizontalGroup(
            fancyPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel31Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        fancyPanel31Layout.setVerticalGroup(
            fancyPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel31Layout.createSequentialGroup()
                .addComponent(fancyLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel10.setText("Ms.Regane Macahibag");

        javax.swing.GroupLayout hciPanelLayout = new javax.swing.GroupLayout(hciPanel);
        hciPanel.setLayout(hciPanelLayout);
        hciPanelLayout.setHorizontalGroup(
            hciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hciPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fancyPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(hciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hcibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        hciPanelLayout.setVerticalGroup(
            hciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hciPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(hciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hciPanelLayout.createSequentialGroup()
                        .addGroup(hciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fancyLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(hciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hcibtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(fancyPanel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hciPanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        cc104Panel.setBorderColor(new java.awt.Color(0, 0, 0));
        cc104Panel.setBorderEnabled(true);
        cc104Panel.setBorderThickness(2.0F);
        cc104Panel.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        cc104Panel.setSolidBackgroundEnabled(true);

        cc104btn.setText("Register");
        cc104btn.setBackgroundColor(new java.awt.Color(0, 0, 0));
        cc104btn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        cc104btn.addActionListener(this::cc104btnActionPerformed);

        fancyLabel50.setText("Data Structures and Algorithms");

        fancyLabel51.setText("Fri-Face to face - MV 304 6:00–8:00 AM· | Sat- Virtual Classrom 6:00–8:00 AM · 3 units");

        fancyPanel35.setGradientEnabled(false);
        fancyPanel35.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel35.setSolidBackgroundEnabled(true);

        fancyLabel52.setText("CC104");
        fancyLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel35Layout = new javax.swing.GroupLayout(fancyPanel35);
        fancyPanel35.setLayout(fancyPanel35Layout);
        fancyPanel35Layout.setHorizontalGroup(
            fancyPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel35Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fancyPanel35Layout.setVerticalGroup(
            fancyPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel35Layout.createSequentialGroup()
                .addComponent(fancyLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel13.setText("Mr.Jayboy Colo");

        javax.swing.GroupLayout cc104PanelLayout = new javax.swing.GroupLayout(cc104Panel);
        cc104Panel.setLayout(cc104PanelLayout);
        cc104PanelLayout.setHorizontalGroup(
            cc104PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cc104PanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fancyPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(cc104PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cc104PanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(cc104PanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(cc104btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cc104PanelLayout.setVerticalGroup(
            cc104PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cc104PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cc104PanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(cc104PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cc104PanelLayout.createSequentialGroup()
                        .addGroup(cc104PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cc104btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyPanel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(cc104PanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        iptPanel.setBorderColor(new java.awt.Color(0, 0, 0));
        iptPanel.setBorderEnabled(true);
        iptPanel.setBorderThickness(2.0F);
        iptPanel.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        iptPanel.setSolidBackgroundEnabled(true);

        ipt101btn.setText("Register");
        ipt101btn.setBackgroundColor(new java.awt.Color(0, 0, 0));
        ipt101btn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        ipt101btn.addActionListener(this::ipt101btnActionPerformed);

        fancyLabel56.setText("Integrative Programming and Technologies");

        fancyLabel57.setText("Fri-Face to face - MV 304 8:30–10:30 AM· | Sat- Virtual Classrom 8:00–10:00 AM · 3 units");

        fancyPanel39.setGradientEnabled(false);
        fancyPanel39.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel39.setSolidBackgroundEnabled(true);

        fancyLabel58.setText("IPT101");
        fancyLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel39Layout = new javax.swing.GroupLayout(fancyPanel39);
        fancyPanel39.setLayout(fancyPanel39Layout);
        fancyPanel39Layout.setHorizontalGroup(
            fancyPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel39Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        fancyPanel39Layout.setVerticalGroup(
            fancyPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel39Layout.createSequentialGroup()
                .addComponent(fancyLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel47.setText("Mr.Romel Cabiling");

        javax.swing.GroupLayout iptPanelLayout = new javax.swing.GroupLayout(iptPanel);
        iptPanel.setLayout(iptPanelLayout);
        iptPanelLayout.setHorizontalGroup(
            iptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iptPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fancyPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(iptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iptPanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(iptPanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(ipt101btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        iptPanelLayout.setVerticalGroup(
            iptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iptPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(iptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iptPanelLayout.createSequentialGroup()
                        .addGroup(iptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fancyLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ipt101btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iptPanelLayout.createSequentialGroup()
                        .addComponent(fancyPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        pePanel.setBorderColor(new java.awt.Color(0, 0, 0));
        pePanel.setBorderEnabled(true);
        pePanel.setBorderThickness(2.0F);
        pePanel.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        pePanel.setSolidBackgroundEnabled(true);

        pe3btn.setText("Register");
        pe3btn.setBackgroundColor(new java.awt.Color(0, 0, 0));
        pe3btn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        pe3btn.addActionListener(this::pe3btnActionPerformed);

        fancyLabel59.setText("Individual and Dual Sports");

        fancyLabel60.setText("Wed-Face to face - MV 304  10:30–12:30 AM · 2units");

        fancyPanel41.setGradientEnabled(false);
        fancyPanel41.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel41.setSolidBackgroundEnabled(true);

        fancyLabel61.setText("PE3");
        fancyLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel41Layout = new javax.swing.GroupLayout(fancyPanel41);
        fancyPanel41.setLayout(fancyPanel41Layout);
        fancyPanel41Layout.setHorizontalGroup(
            fancyPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel41Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        fancyPanel41Layout.setVerticalGroup(
            fancyPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel41Layout.createSequentialGroup()
                .addComponent(fancyLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel12.setText("Ms.Rose Ann Icaonapo");

        javax.swing.GroupLayout pePanelLayout = new javax.swing.GroupLayout(pePanel);
        pePanel.setLayout(pePanelLayout);
        pePanelLayout.setHorizontalGroup(
            pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pePanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fancyPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pePanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fancyLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pe3btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pePanelLayout.setVerticalGroup(
            pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pePanelLayout.createSequentialGroup()
                        .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fancyLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fancyLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pePanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(pe3btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        itePanel.setBorderColor(new java.awt.Color(0, 0, 0));
        itePanel.setBorderEnabled(true);
        itePanel.setBorderThickness(2.0F);
        itePanel.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        itePanel.setSolidBackgroundEnabled(true);

        ite1btn.setText("Register");
        ite1btn.setBackgroundColor(new java.awt.Color(0, 0, 0));
        ite1btn.setDefaultForeground(new java.awt.Color(255, 255, 255));
        ite1btn.addActionListener(this::ite1btnActionPerformed);

        fancyLabel62.setText("IT Elective 1 (Web Fundamental)");

        fancyLabel63.setText("Fri-Face to face - MV 304 10:30–12:30 AM· | Sat- Virtual Classrom 10:00–12:00 AM · 3 units");

        fancyPanel43.setGradientEnabled(false);
        fancyPanel43.setSolidBackgroundColor(new java.awt.Color(204, 204, 204));
        fancyPanel43.setSolidBackgroundEnabled(true);

        fancyLabel64.setText("ITE1");
        fancyLabel64.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout fancyPanel43Layout = new javax.swing.GroupLayout(fancyPanel43);
        fancyPanel43.setLayout(fancyPanel43Layout);
        fancyPanel43Layout.setHorizontalGroup(
            fancyPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel43Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fancyLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        fancyPanel43Layout.setVerticalGroup(
            fancyPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel43Layout.createSequentialGroup()
                .addComponent(fancyLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        fancyLabel48.setText("Ms.Kris Villaflores");

        javax.swing.GroupLayout itePanelLayout = new javax.swing.GroupLayout(itePanel);
        itePanel.setLayout(itePanelLayout);
        itePanelLayout.setHorizontalGroup(
            itePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itePanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fancyPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(itePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(938, 938, 938)
                .addComponent(fancyLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(ite1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        itePanelLayout.setVerticalGroup(
            itePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itePanelLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(itePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itePanelLayout.createSequentialGroup()
                        .addComponent(fancyLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fancyLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itePanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(fancyPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
            .addGroup(itePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(itePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ite1btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel3Layout = new javax.swing.GroupLayout(fancyPanel3);
        fancyPanel3.setLayout(fancyPanel3Layout);
        fancyPanel3Layout.setHorizontalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ms102Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hciPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soslitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cc104Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(net101Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel3Layout.setVerticalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(net101Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ms102Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(hciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(soslitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cc104Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(iptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(itePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        fancyButton2.setText("AY 2026–2027 · 1st Semester");
        fancyButton2.setBackgroundColor(new java.awt.Color(102, 255, 0));

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fancyPanel1Layout.createSequentialGroup()
                                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                                        .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jSeparator1))
                                .addContainerGap())
                            .addGroup(fancyPanel1Layout.createSequentialGroup()
                                .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fancyPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mycoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycoursesActionPerformed
        new MyCourses(loggedInStudentID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mycoursesActionPerformed

    private void coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesActionPerformed
        new Courses(loggedInStudentID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_coursesActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        new Profile(loggedInStudentID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure to logout", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        new Dashboard(loggedInStudentID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardActionPerformed

    private void registerbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtn3ActionPerformed

    private void ms102btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms102btnActionPerformed
        DBConn db = new DBConn();

        boolean saved = db.saveCourse(
                loggedInStudentID,
                "MS102",
                "Qauntitative Methods with Modelling Simulation",
                "Mon-Face to face - MV 304 8:30–10:30 AM· | Tue- Virtual Classrom 8:00–9:00 AM · 3 units",
                "Mr.Cesar Canlas",
                "Active"
        );

        if (saved) {
            JOptionPane.showMessageDialog(
                    this,
                    "MS102 successfully registered!"
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "You already have it."
            );
        }
    }//GEN-LAST:event_ms102btnActionPerformed

    private void registerbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtn10ActionPerformed

    private void net101btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_net101btnActionPerformed
        DBConn db = new DBConn();

        if (!db.isCourseAvailable("NET101")) {
            JOptionPane.showMessageDialog(
                    this,
                    "NET101 is no longer available."
            );
            return;
        }
        if (db.isCourseRegistered(loggedInStudentID, "NET101")) {
            JOptionPane.showMessageDialog(
                    this,
                    "NET101 is already registered!"
            );
            return;
        }

        boolean saved = db.saveCourse(
                loggedInStudentID,
                "NET101",
                "Networking 1",
                "Mon-Face to face - MV 304 6:00-8:00 AM | Tue-Virtual Classroom 7:00-8:00 AM",
                "Mr.Aldrine De Guzman",
                "Active"
        );

        if (saved) {
            JOptionPane.showMessageDialog(
                    this,
                    "NET101 successfully registered!"
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "You already have it."
            );
        }
    }//GEN-LAST:event_net101btnActionPerformed

    private void soslitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soslitbtnActionPerformed
        DBConn db = new DBConn();

        if (!db.isCourseAvailable("SOSLIT")) {
            JOptionPane.showMessageDialog(
                    this,
                    "SOSLIT is no longer available."
            );
            return;
        }
        if (db.isCourseRegistered(loggedInStudentID, "SOSLIT")) {
            JOptionPane.showMessageDialog(
                    this,
                    "SOSLIT is already registered!"
            );
            return;
        }

        boolean saved = db.saveCourse(
                loggedInStudentID,
                "SOSLIT",
                "Sosyedad at Literatura",
                "Wed-Face to face - MV 304 08:30–10:30 AM· | Th- Virtual Classrom 8:00–9:00 AM · 3 units",
                "Ms.Azucena S. Lim",
                "Active"
        );

        if (saved) {
            JOptionPane.showMessageDialog(
                    this,
                    "SOSLIT successfully registered!"
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "You already have it."
            );
        }
    }//GEN-LAST:event_soslitbtnActionPerformed

    private void hcibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcibtnActionPerformed
        DBConn db = new DBConn();

        if (!db.isCourseAvailable("HCI101")) {
            JOptionPane.showMessageDialog(
                    this,
                    "HCI101 is no longer available."
            );
            return;
        }
        if (db.isCourseRegistered(loggedInStudentID, "HCI101")) {
            JOptionPane.showMessageDialog(
                    this,
                    "HCI101 is already registered!"
            );
            return;
        }

        boolean saved = db.saveCourse(
                loggedInStudentID,
                "HCI101",
                "Introduction to Human Computer",
                "Mon-Face to face - MV 304 10:30–12:30 AM· | Tue- Virtual Classrom 9:00–10:00 AM · 3 units",
                "Ms.Regane Macahibag",
                "Active"
        );

        if (saved) {
            JOptionPane.showMessageDialog(
                    this,
                    "HCI101 successfully registered!"
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "You already have it."
            );
        }
    }//GEN-LAST:event_hcibtnActionPerformed

    private void cc104btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc104btnActionPerformed
        DBConn db = new DBConn();

        if (!db.isCourseAvailable("CC104")) {
            JOptionPane.showMessageDialog(
                    this,
                    "CC104 is no longer available."
            );
            return;
        }
        if (db.isCourseRegistered(loggedInStudentID, "CC104")) {
            JOptionPane.showMessageDialog(
                    this,
                    "CC104 is already registered!"
            );
            return;
        }

        boolean saved = db.saveCourse(
                loggedInStudentID,
                "CC104",
                "Data Structures and Algorithms",
                "Fri-Face to face - MV 304 6:00–8:00 AM· | Sat- Virtual Classrom 6:00–8:00 AM · 3 units",
                "Mr.Jayboy Colo",
                "Active"
        );

        if (saved) {
            JOptionPane.showMessageDialog(
                    this,
                    "CC104 successfully registered!"
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "You already have it."
            );
        }
    }//GEN-LAST:event_cc104btnActionPerformed

    private void registerbtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtn16ActionPerformed
        
    }//GEN-LAST:event_registerbtn16ActionPerformed

    private void ipt101btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipt101btnActionPerformed
        DBConn db = new DBConn();

        if (!db.isCourseAvailable("IPT101")) {
            JOptionPane.showMessageDialog(
                    this,
                    "IPT101 is no longer available."
            );
            return;
        }
        if (db.isCourseRegistered(loggedInStudentID, "IPT101")) {
            JOptionPane.showMessageDialog(
                    this,
                    "IPT101 is already registered!"
            );
            return;
        }

        boolean saved = db.saveCourse(
                loggedInStudentID,
                "IPT101",
                "Integrative Programming and Technologies",
                "Fri-Face to face - MV 304 8:30–10:30 AM· | Sat- Virtual Classrom 8:00–10:00 AM · 3 units",
                "Mr.Romel Cabiling",
                "Active"
        );

        if (saved) {
            JOptionPane.showMessageDialog(
                    this,
                    "IPT101 successfully registered!"
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "You already have it."
            );
        }
    }//GEN-LAST:event_ipt101btnActionPerformed

    private void pe3btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pe3btnActionPerformed
        DBConn db = new DBConn();

        if (!db.isCourseAvailable("PE3")) {
            JOptionPane.showMessageDialog(
                    this,
                    "PE3 is no longer available."
            );
            return;
        }
        if (db.isCourseRegistered(loggedInStudentID, "PE3")) {
            JOptionPane.showMessageDialog(
                    this,
                    "PE3 is already registered!"
            );
            return;
        }

        boolean saved = db.saveCourse(
                loggedInStudentID,
                "PE3",
                "Individual and Dual Sports",
                "Wed-Face to face - MV 304  10:30–12:30 AM · 2units",
                "Ms.Rose Ann Icaonapo",
                "Active"
        );

        if (saved) {
            JOptionPane.showMessageDialog(
                    this,
                    "PE3 successfully registered!"
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "You already have it."
            );
        }
    }//GEN-LAST:event_pe3btnActionPerformed

    private void ite1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ite1btnActionPerformed
        // System.out.println("Logged-in Student ID: [" + loggedInStudentID + "]");

        DBConn db = new DBConn();
        if (!db.isCourseAvailable("ITEI")) {
            JOptionPane.showMessageDialog(
                    this,
                    "ITEI is no longer available."
            );
            return;
        }
        if (db.isCourseRegistered(loggedInStudentID, "ITE1")) {
            JOptionPane.showMessageDialog(
                    this,
                    "ITE1 is already registered!"
            );
            return;
        }

        boolean saved = db.saveCourse(
                loggedInStudentID,
                "ITE1",
                "IT Elective 1 (Web Fundamental)",
                "Fri-Face to face - MV 304 10:30–12:30 AM· | Sat- Virtual Classrom 10:00–12:00 AM · 3 units",
                "Ms.Kris Villaflores",
                "Active"
        );

        if (saved) {
            JOptionPane.showMessageDialog(
                    this,
                    "ITE1 successfully registered!"
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "You already have it."
            );
        }
    }//GEN-LAST:event_ite1btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Courses().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyPanel cc104Panel;
    private fancyui.FancyButton cc104btn;
    private fancyui.FancyButton courses;
    private fancyui.FancyButton dashboard;
    private fancyui.FancyButton fancyButton2;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyLabel fancyLabel10;
    private fancyui.FancyLabel fancyLabel11;
    private fancyui.FancyLabel fancyLabel12;
    private fancyui.FancyLabel fancyLabel13;
    private fancyui.FancyLabel fancyLabel14;
    private fancyui.FancyLabel fancyLabel15;
    private fancyui.FancyLabel fancyLabel16;
    private fancyui.FancyLabel fancyLabel2;
    private fancyui.FancyLabel fancyLabel3;
    private fancyui.FancyLabel fancyLabel32;
    private fancyui.FancyLabel fancyLabel33;
    private fancyui.FancyLabel fancyLabel34;
    private fancyui.FancyLabel fancyLabel35;
    private fancyui.FancyLabel fancyLabel36;
    private fancyui.FancyLabel fancyLabel37;
    private fancyui.FancyLabel fancyLabel38;
    private fancyui.FancyLabel fancyLabel39;
    private fancyui.FancyLabel fancyLabel40;
    private fancyui.FancyLabel fancyLabel41;
    private fancyui.FancyLabel fancyLabel42;
    private fancyui.FancyLabel fancyLabel43;
    private fancyui.FancyLabel fancyLabel44;
    private fancyui.FancyLabel fancyLabel45;
    private fancyui.FancyLabel fancyLabel46;
    private fancyui.FancyLabel fancyLabel47;
    private fancyui.FancyLabel fancyLabel48;
    private fancyui.FancyLabel fancyLabel5;
    private fancyui.FancyLabel fancyLabel50;
    private fancyui.FancyLabel fancyLabel51;
    private fancyui.FancyLabel fancyLabel52;
    private fancyui.FancyLabel fancyLabel53;
    private fancyui.FancyLabel fancyLabel54;
    private fancyui.FancyLabel fancyLabel55;
    private fancyui.FancyLabel fancyLabel56;
    private fancyui.FancyLabel fancyLabel57;
    private fancyui.FancyLabel fancyLabel58;
    private fancyui.FancyLabel fancyLabel59;
    private fancyui.FancyLabel fancyLabel60;
    private fancyui.FancyLabel fancyLabel61;
    private fancyui.FancyLabel fancyLabel62;
    private fancyui.FancyLabel fancyLabel63;
    private fancyui.FancyLabel fancyLabel64;
    private fancyui.FancyLabel fancyLabel8;
    private fancyui.FancyLabel fancyLabel9;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel10;
    private fancyui.FancyPanel fancyPanel11;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel23;
    private fancyui.FancyPanel fancyPanel24;
    private fancyui.FancyPanel fancyPanel25;
    private fancyui.FancyPanel fancyPanel27;
    private fancyui.FancyPanel fancyPanel29;
    private fancyui.FancyPanel fancyPanel3;
    private fancyui.FancyPanel fancyPanel31;
    private fancyui.FancyPanel fancyPanel35;
    private fancyui.FancyPanel fancyPanel36;
    private fancyui.FancyPanel fancyPanel37;
    private fancyui.FancyPanel fancyPanel39;
    private fancyui.FancyPanel fancyPanel41;
    private fancyui.FancyPanel fancyPanel43;
    private fancyui.FancyPanel hciPanel;
    private fancyui.FancyButton hcibtn;
    private fancyui.FancyButton ipt101btn;
    private fancyui.FancyPanel iptPanel;
    private fancyui.FancyButton ite1btn;
    private fancyui.FancyPanel itePanel;
    private javax.swing.JSeparator jSeparator1;
    private fancyui.FancyButton logout;
    private fancyui.FancyPanel ms102Panel;
    private fancyui.FancyButton ms102btn;
    private fancyui.FancyButton mycourses;
    private fancyui.FancyPanel net101Panel;
    private fancyui.FancyButton net101btn;
    private fancyui.FancyButton pe3btn;
    private fancyui.FancyPanel pePanel;
    private fancyui.FancyButton profile;
    private fancyui.FancyPanel register;
    private fancyui.FancyButton registerbtn10;
    private fancyui.FancyButton registerbtn16;
    private fancyui.FancyButton registerbtn3;
    private fancyui.FancyPanel soslitPanel;
    private fancyui.FancyButton soslitbtn;
    // End of variables declaration//GEN-END:variables
}
